import React from 'react';
import type { Metadata } from 'next';
import { Breadcrumbs } from '@/components/layout/Breadcrumbs';
import { AlertCircle } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Calculator Accuracy Disclaimer | ToolNest',
  description: 'Important legal and accuracy disclaimer regarding ToolNest calculators, financial estimates, health formulas, and tools.',
};

export default function DisclaimerPage() {
  return (
    <div className="w-full max-w-4xl mx-auto pb-16">
      <Breadcrumbs items={[{ name: 'Disclaimer', url: '/disclaimer' }]} />

      <div className="rounded-3xl border border-zinc-200 bg-white p-8 sm:p-12 dark:border-zinc-800 dark:bg-zinc-900/60 shadow-xs space-y-6">
        <div className="flex items-center gap-3">
          <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-amber-100 text-amber-600 dark:bg-amber-950 dark:text-amber-400">
            <AlertCircle className="h-5 w-5" />
          </div>
          <div>
            <h1 className="text-2xl sm:text-3xl font-black text-zinc-900 dark:text-zinc-50">
              Disclaimer & Accuracy Notice
            </h1>
            <span className="text-xs text-zinc-400">Last updated: September 2026</span>
          </div>
        </div>

        <section className="space-y-3 text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed">
          <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">1. Informational & Educational Use Only</h2>
          <p>
            The calculators, converters, statistical engines, and utilities on ToolNest are provided strictly for general educational and informational purposes. While we take meticulous care to ensure our algorithms adhere to standard mathematical and engineering formulas, calculations should be independently verified before making critical financial, academic, medical, or legal commitments.
          </p>
        </section>

        <section className="space-y-3 text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed">
          <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">2. Financial & Tax Calculations</h2>
          <p>
            Calculators estimating Loan EMI, salary take-home, GST, compound interest, and investment returns use standardized mathematical models. Actual payroll deductions, statutory tax slabs, banking fees, and lender amortization conventions vary significantly by country, jurisdiction, and individual tax status. ToolNest does not provide certified financial, accounting, or tax advice.
          </p>
        </section>

        <section className="space-y-3 text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed">
          <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">3. Health & Fitness Calculations</h2>
          <p>
            The Body Mass Index (BMI) calculator uses standard World Health Organization (WHO) formulas. BMI is an approximate population-level screening benchmark and does not evaluate body fat percentage, muscular build, bone density, or clinical wellness. Always consult a qualified healthcare professional for personalized medical guidance.
          </p>
        </section>

        <section className="space-y-3 text-sm text-zinc-600 dark:text-zinc-300 leading-relaxed">
          <h2 className="text-base font-bold text-zinc-900 dark:text-zinc-100">4. Limitation of Liability</h2>
          <p>
            ToolNest and its developers assume no liability for any errors, omissions, or consequences resulting from decisions made in reliance on calculations or text outputs generated by the platform.
          </p>
        </section>
      </div>
    </div>
  );
}
